# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=500, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='description of purpose', width_field='width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summaryImage',
            field=models.ImageField(blank=True, height_field='height', max_length=500, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='description of purpose', width_field='width'),
        ),
    ]
