# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171027_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='%Y/%m/%d/', verbose_name='description of purpose'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summaryImage',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='%Y/%m/%d/', verbose_name='description of purpose'),
        ),
    ]
