# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171028_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='width',
        ),
    ]
